"""add alerts table

Revision ID: 25f3797d9603
Revises: 0e10fbd531b9
Create Date: 2026-05-14 23:13:17.061302

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "25f3797d9603"
down_revision: str | Sequence[str] | None = "0e10fbd531b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
