"""add composite indexes

Revision ID: 3df864ebe021
Revises: 9ee30defe6f6
Create Date: 2026-05-30 16:00:04.180798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df864ebe021'
down_revision: Union[str, Sequence[str], None] = '9ee30defe6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alerts_device_id_status', 'alerts', ['device_id', 'status'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_device_events_device_id_created_at', 'device_events', ['device_id', 'created_at'], unique=False)
    op.create_index('ix_device_events_event_type', 'device_events', ['event_type'], unique=False)
    op.create_index('ix_device_metrics_device_id_checked_at', 'device_metrics', ['device_id', 'checked_at'], unique=False)
    op.create_index('ix_snmp_snapshots_device_id_collected_at', 'device_snmp_system_snapshots', ['device_id', 'collected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snmp_snapshots_device_id_collected_at', table_name='device_snmp_system_snapshots')
    op.drop_index('ix_device_metrics_device_id_checked_at', table_name='device_metrics')
    op.drop_index('ix_device_events_event_type', table_name='device_events')
    op.drop_index('ix_device_events_device_id_created_at', table_name='device_events')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_device_id_status', table_name='alerts')
    # ### end Alembic commands ###
