"""add jitter metric

Revision ID: 710a5704e505
Revises: e87749efd30d
Create Date: 2026-06-13 17:48:11.435652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710a5704e505'
down_revision: Union[str, Sequence[str], None] = 'e87749efd30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_metrics', sa.Column('jitter_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_metrics', 'jitter_ms')
    # ### end Alembic commands ###
