"""add device events table

Revision ID: 9ee30defe6f6
Revises: 39276b471c4b
Create Date: 2026-05-15 00:18:14.513068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee30defe6f6'
down_revision: Union[str, Sequence[str], None] = '39276b471c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('DEVICE_ONLINE', 'DEVICE_OFFLINE', 'ALERT_CREATED', 'ALERT_ACKNOWLEDGED', 'ALERT_RESOLVED', 'SNMP_SNAPSHOT_COLLECTED', name='deviceeventtype'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_events_id'), 'device_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_events_id'), table_name='device_events')
    op.drop_table('device_events')
    # ### end Alembic commands ###
