"""add packet loss metric

Revision ID: e87749efd30d
Revises: f15781ed98e2
Create Date: 2026-05-31 21:35:44.860461

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e87749efd30d"
down_revision: str | Sequence[str] | None = "f15781ed98e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device_metrics", sa.Column("packet_loss_percent", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device_metrics", "packet_loss_percent")
    # ### end Alembic commands ###
